//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BobsCNC_Speeds_and_Feeds.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Evolution Series - Makita")]
        public string Model {
            get {
                return ((string)(this["Model"]));
            }
            set {
                this["Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hardwood")]
        public string Material {
            get {
                return ((string)(this["Material"]));
            }
            set {
                this["Material"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inches")]
        public string Units {
            get {
                return ((string)(this["Units"]));
            }
            set {
                this["Units"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calculating Speeds and Feeds\r\n\r\nIt is important to note that there are many varia" +
            "bles when setting CNC cutting parameters. The values set should be thought of a " +
            "starting values.  With experience, these values can be modified to find the swee" +
            "t spot for the project that you are working on.\r\n\r\nCalculation details:\r\n\r\nSurfa" +
            "ce Feet per Minute (SFM) Is a number that sets the best RPM for cutting the mate" +
            "rial. This number varies depending on the manufacture of the tool and CNC machin" +
            "e. The calculation is:\r\n\r\n                SFM = RPM x 0.2618 x bit diameter (inc" +
            "hes)\r\n\r\n We have added default SFM values. If SFM value is modified, it will cha" +
            "nge the RPM of the spindle.\r\n\r\nOnce the RPM is determined, you can calculate the" +
            " feed rate with the formula\r\n\r\n                Feed Rate = RPM x Flute count x C" +
            "hip load\r\n\r\nThe flute count is the number of flutes on the bit, and the chip loa" +
            "d is the size of the chip being removed. If the chip load value is modified, it " +
            "will change the feed rate.\r\n\r\nThe plunge rate determines the feed rate of the Z " +
            "axis as the bit plunges into the material. A good rule of thumb is to set the pl" +
            "unge rate to 1/2 the feed rate. \r\n\r\n                Plunge Rate = 0.5 x Feed Rat" +
            "e\r\n\r\nThe step over is the space between the passes. The default step over value " +
            "is set to 0.3 x bit diameter.  Stepover should be between 0.1 and 0.3 of the bit" +
            " diameter\r\n\r\n               Stepover = 0.3 X bit diameter\r\n\r\nDepth per pass is d" +
            "etermined by the CNC and the bit diameter. Larger heavy-duty CNC\'s can cut deepe" +
            "r per pass while smaller and lighter duty CNCs will cut at less depth per pass.\r" +
            "\n")]
        public string Details {
            get {
                return ((string)(this["Details"]));
            }
            set {
                this["Details"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"There is a learning curve for cutting aluminum. The sweet spot for the cutting parameters is small and any deviation will reduce cutting quality and may damage the bit or workpiece.  We would recommend”

- 30 psi of air flow through a nozzle as a minimum.  Mist cooling would be a better alternative. The bit needs to be kept cool and the chips need to be removed from the cutting area quickly.

-  O-flute or single flute bit designed to cut aluminum. The high helix angle helps remove chips and the low flute count helps keep the feed rate manageable for higher RPMs.

- The bit should be no larger than 1/8"" (3mm) cutting diameter.

- The workpiece must to be securely clamped to hold it in place and reduce any vibrations (If the part vibrates the cutting performance will be reduced and bit damage can occur.

- There is an small range of optimal cut depths.  Cutting too deep will cause deflection or bit breakage and cutting too light will cause rubbing and heat buildup which will dull a bit.

- If the feed rate is too slow, the aluminum can melt and built up on the bit, if the feed rate is too fast the bit may break.

**************************************************************")]
        public string WMA1 {
            get {
                return ((string)(this["WMA1"]));
            }
            set {
                this["WMA1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E Series has a fixed RPM.  The feed rate and plunge rate have been adjusted for t" +
            "his RPM.\r\n\r\n**************************************************************")]
        public string WMA2 {
            get {
                return ((string)(this["WMA2"]));
            }
            set {
                this["WMA2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Small bits can break easily. Reduce feed rate and depth of cut for longer bits wi" +
            "th small diameters.\r\n\r\n*********************************************************" +
            "*****\r\n\r\n\r\n")]
        public string WMA3 {
            get {
                return ((string)(this["WMA3"]));
            }
            set {
                this["WMA3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Large bits that are incorrectly set up can cause damage to the CNC and work piece" +
            ". Reduce feed rate, stepover, and depth per pass.\r\n\r\n***************************" +
            "***********************************\r\n")]
        public string WMA4 {
            get {
                return ((string)(this["WMA4"]));
            }
            set {
                this["WMA4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNC routers spin at a high RPM.  One or two flutes are recommended for most mater" +
            "ials.  An O-flute or single flute bit is recommended for cutting aluminum.\r\n\r\n\r\n" +
            "**************************************************************")]
        public string WMA5 {
            get {
                return ((string)(this["WMA5"]));
            }
            set {
                this["WMA5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chip loads above 0.040\" (1mm) are not recommended.\r\n\r\n\r\n*************************" +
            "*************************************")]
        public string WMA6 {
            get {
                return ((string)(this["WMA6"]));
            }
            set {
                this["WMA6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.125")]
        public string BitDiameter {
            get {
                return ((string)(this["BitDiameter"]));
            }
            set {
                this["BitDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"The spindle is not capable of spinning at this high of RPM.  The feed and plunge rate have been determined using the highest RPM for the selected spindle.  A larger diameter bit or a bit with more flutes until the optimal RPM can be set is recommended.



**************************************************************

")]
        public string WMA7 {
            get {
                return ((string)(this["WMA7"]));
            }
            set {
                this["WMA7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"The spindle is not capable of spinning at this low of RPM.  The feed and plunge rate have been determined using the lowest RPM for the selected spindle.  A smaller diameter bit or a bit with less flutes until the optimal RPM can be set is recommended.



**************************************************************


")]
        public string WMA8 {
            get {
                return ((string)(this["WMA8"]));
            }
            set {
                this["WMA8"] = value;
            }
        }
    }
}
